### ISSUE TITLE
Roli Seaboard Rise 25: gate intermittent

### ISSUE THREAD

**Issue by shroom2ma** [bafonso/Erratic#1]
Gate only seems to be outputting on certain notes.   I can pitch track fine once I've found a note that registers a gate, so that part seems ok.  The pressure and axis tracking seems to work as expected too.

I've set the pitch tracking to match my roli dashboard, and MPE is on etc.  All the context menu settings are set to ROLI stds.  MIDI Channel is 2 (set to 2-16 on the roli dashboard).

**Comment by bafonso** [comment]
Can you set to channel two only? It's likely going through all channels instead of just channel two.

**Comment by shroom2ma** [comment]
In MPE mode, you can only set a range.  The smallest being 2..3

If I set it to that, I can't seem to find any key that produces a gate.

**Comment by bafonso** [comment]
Can you use the program midi monitor and save the output from rise?

**Comment by shroom2ma** [comment]
Good idea!  I'll send you a report if I get chance tomorrow (getting late
here!)

**Comment by shroom2ma** [comment]
Hi there.   I've attached the output from MIDI-OX.

The first note (F2) was the only one that produced a gate.   I held it a short time, then pressed some other random notes for a similar length.

Also I've noticed another slight possible bug - the global channel selection in the context menu seems to revert back to 16 - Haken Continuum whenever I reload the patch.  Not a major thing, and it didn't actually seem to stop what is working from working, but thought you might want to know.

MIDI debug info:
[midioutdbg.txt](https://github.com/bafonso/MPE/files/1704754/midioutdbg.txt)

Regards

**Comment by bafonso** [comment]
The MPEToCV is a monophonic MPE converter so you will need to set in the ROLI dashboard to use a single channel and select only channel 2. I will probably create an option where I will parse all channels 2-16 and just pick the last note played.

**Comment by bafonso** [comment]
I will add the menu settings to be recalled once you reload the project, I forgot to do that to the monophonic version.

**Comment by shroom2ma** [comment]
Put this down to user error!   Switched off the MPE mode and it works.   I'm an idiot!
