### ISSUE TITLE
0.6.1 - Windows binary here!

### ISSUE THREAD

**Issue by DomiKamu** [bafonso/Erratic#4]
[ErraticInstruments-0.6.1-win.zip](https://github.com/bafonso/Erratic/files/1918849/ErraticInstruments-0.6.1-win.zip)

**Comment by bafonso** [comment]
Thanks, I will upload it :)

**Comment by thoughtfuzz** [comment]
I built 0.6.2 windows for myself,
for anyone lazy:
[ErraticInstruments-0.6.2-win.zip](https://github.com/bafonso/Erratic/files/2933599/ErraticInstruments-0.6.2-win.zip)
