### ISSUE TITLE
Does not run in Rack 0.6.1

### ISSUE THREAD

**Issue by AndrewBelt** [bafonso/Erratic#7]
The new Rack Midi API is now available in `include/midi.hpp`, but this plugin seems to use the old MidiIO API from Rack 0.5. It will therefore not load in Rack 0.6.1.
See the `src/Core/*.cpp` files for example usage.

**Comment by bafonso** [comment]
I will definitely look into this as I was under the impression I was using the same approach as the new midi modules in 0.6!

**Comment by bafonso** [comment]
I've updated to the new API and it should work fine now.
